[package]
name = "api"
version = "0.1.0"
edition = "2024"
authors = ["E"]

[dependencies]
actix-web = "4.9.0"
dotenvy = "0.15.7"
sea-orm = { version = "1.1.0", features = [ "sqlx-postgres", "runtime-tokio-native-tls", "macros", "with-json", "with-uuid" ] }#

database = { path = "../database" }